server:
    port: 8090
    servlet:
        context-path: /user
spring:
    cloud:
        nacos:
            # nacos 服务注册地址
            server-addr: localhost:8848 # nacos 服务器地址
            discovery:
                # 服务集群
                cluster-name: BJ
    application:
        # 服务的名字
        name: user-service
    # 数据库配置
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/micro_service?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
        username: root
        password: 123123123
        druid:
            max-active: 20
            initial-size: 5

mybatis:
    mapper-locations: classpath:/mapper/**/*.xml

